### ISSUE TITLE
Setting too long title in the forums will show a non user friendly error

### ISSUE THREAD

**Issue by Trosk** [ppy/osu-web#1620]
It will also not let you use tags in Help / Feature Requests if the thread name is too long.

![chrome_2017-10-23_13-57-48](https://user-images.githubusercontent.com/15179452/31888055-d9c4c9e2-b7fa-11e7-8bb3-44aea512b219.png)

**Comment by nanaya** [comment]
This has been fixed.

**Comment by E223** [comment]
It seems you still can't use tags if the thread name is too long. Should a new issue be opened since that was only briefly mentioned in this one?
