### ISSUE TITLE
Ampersands show `&amp;` instead of `&` in forum names

### ISSUE THREAD

**Issue by Nath789** [ppy/osu-web#1897]
![image](https://user-images.githubusercontent.com/5668486/33610354-36f42338-da06-11e7-83cf-3d207ab57d48.png)

![image](https://user-images.githubusercontent.com/5668486/33610738-3b1c5880-da07-11e7-86e2-ce65262e2f9b.png)

This didn't happen in the forum index.

**Comment by nanaya** [comment]
Database need updating. Same reason as topic titles.

**Comment by peppy** [comment]
Fixed.

**Comment by E223** [comment]
This is still broken in subforums of Gameplay & Rankings
![](https://death.s-ul.eu/63KGxgtF.png)
![](https://death.s-ul.eu/KYa7lRME.png)

**Comment by peppy** [comment]
Thanks for pointing this out! Has also been fixed.
