### ISSUE TITLE
Chart leaderboard score bugged for mania mode

### ISSUE THREAD

**Issue by Shadowthegod** [ppy/osu-web#5530]
Mania Spotlights leaderboard for Summer season got bugged and some people have more score then they should have. For 8 mapsets with 23 total difficulties, they have over 8 million and the top1 has 23 million which matches the total difficulty count. Even though he is under the #3 player on the leaderboard on all individual difficulties.

For some reason, probably all difficulties are counted towards the total score while the intended should be that it only counts the highest score reached. This issue is very similar to the one happened in the past and it is a problem because I am giving out rewards based on this ranking.

**Comment by cl8n** [comment]
his Ranked score is slightly higher than the max possible across all of these maps, so it's definitely not (only?) counting all diffs, something else is wrong too

**Comment by peppy** [comment]
Hmm, I thought this issue was already fixed. Might be something to do with fallback score submissions, will investigate.

**Comment by o2maniac** [comment]
Hi, I'm Cryolien, the guy who got #3 in mania Summer spotlights. Now currently in Autumn spotlights, the issue still persists. However, what I notice is that instead of all difficulties counting toward the score, there's also the issue of being able to set more than 1 score on the same difficulty and having it count towards their score
To verify that, I set a bunch of 0.01% to 1% accuracy scores over and over on a single difficulty
![screenshot411](https://user-images.githubusercontent.com/44362151/73921745-e6d98a00-4902-11ea-8f51-4986dd6aeccf.jpg)
 to achieve this overall accuracy and score:
![ApplicationFrameHost_5gQu9u0tLx](https://user-images.githubusercontent.com/44362151/73921363-2653a680-4902-11ea-9f6c-83ca20c5d112.png)

So all in all, this also might have been what's happening since like 4-5 years ago

**Comment by peppy** [comment]
As an update, I've fixed all existing scores retroactively and am working on a permanent fix for this issue. Thanks for your patience!

**Comment by peppy** [comment]
We've also basically replaced this system with the new "playlists" based spotlights, which uses a much saner way of calculating scores.

Not sure why this wasn't closed yet so let's do that.
