### ISSUE TITLE
BPM display on beatmap page is sometimes off by 0.001

### ISSUE THREAD

**Issue by Purplegaze** [ppy/osu-web#8069]
There are some whole number values that, when used as the BPM of a map, always result in BPM on the beatmap page being unsatisfyingly off by 0.001.

Examples:
294bpm always displays as 293.999 (https://osu.ppy.sh/beatmapsets/663472#mania/2946072)
292bpm always displays as 292.001 (https://osu.ppy.sh/beatmapsets/291783#osu/656915)
(these are not the only values that cause this issue, though it seems to go in the negative direction much more often.)

**Comment by nanaya** [comment]
Oh, I was looking at wrong table/column. It's incorrect in the database and osu-web is just displaying whatever stored in it.

**Comment by peppy** [comment]
Wondering if we should be rounding this at display time either way.. Will need to check what lazer/stable are doing in these cases.

**Comment by peppy** [comment]
I've fixed this at a database and BSS level, should be good now!

**Comment by Purplegaze** [comment]
Still occurs for 292bpm https://osu.ppy.sh/beatmapsets/1577731#osu/3221521

**Comment by peppy** [comment]
The deploy for this change was incorrectly delayed, which means that some submissions may have slipped through the cracks. I've fixed that specific case.

**Comment by Purplegaze** [comment]
After looking at it again, this appears to still be happening for every map uploaded post-fix, not just the one I linked. The most recent map I can find that has one of these BPMs was uploaded 3 days ago, so unless it was re-fixed in the last 3 days, the error still persists on all newly-submitted beatmaps.

**Comment by peppy** [comment]
yes, already aware.

**Comment by peppy** [comment]
I've deployed a permanent fix for this one, and fixed all regressing cases since the last message.
