### ISSUE TITLE
Negative grade counts on profiles

### ISSUE THREAD

**Issue by respektive** [ppy/osu-web#8443]
The original issue https://github.com/ppy/osu-web/issues/7152 has been fixed by https://github.com/ppy/osu-web/pull/7996, but the negative counts still remain today.
![firefox_PoxO6rxWNs](https://user-images.githubusercontent.com/22381687/146062785-fb111dd3-737e-4772-86f3-35358a5266e1.png)
This was supposed to be fixed by a reprocess mentioned in this comment https://github.com/ppy/osu-web/issues/7152#issuecomment-891591192.

**Comment by peppy** [comment]
Said reprocess has not yet been run. If you tell me the user ID here I can fix it for that specific case.

**Comment by respektive** [comment]
I know about 2 users that currently have wrong grade counts, but there are probably many more that just aren't as obvious, because they didn't go into negative. So I'm not sure if it's that important to fix in this specific case, or if it might just be better to fix everyone with a full reprocess in the future. 

Nonetheless I'll give you the two users i know about:
https://osu.ppy.sh/users/5795337
https://osu.ppy.sh/users/14220975

**Comment by peppy** [comment]
I've fixed those two users.

I'll keep this issue open to track the full reprocess task, which is a bit involved currently. Will likely be run after the migration of scores to a new structure, estimated to be done in the next month or two.

**Comment by peppy** [comment]
As an update, I've fixed all negative counts now. The underlying issues causing this has also since been fixed.

A background process is running on all remaining users to ensure consistency, which will take several days. Let me know if anything comes up which requires further attention.

**Comment by Susko3** [comment]
Negative grade counts are still a problem. See [this discord conversation](https://discord.com/channels/188630481301012481/1097318920991559880/1239166334936285255). The profile in question is https://osu.ppy.sh/users/35641744, their A-rank count should be `1`. I'm unsure about what the underlying issue is.

![image](https://github.com/ppy/osu-web/assets/16479013/37f6a839-3fea-4ab6-a525-a77b9f6b8fef)

Some theorise this may be related to lazer/stable scores overwriting each other:
https://discord.com/channels/188630481301012481/1097318920991559880/1239199661198413865.
> As far as I know, you can get negative rank count since lazer pp release in two ways:
> - If you have the same rank as highest score on one map in lazer and stable, overwrite the score in lazer, then in stable (reduces the count 2 times instead of 1)
> - If you have different rank as highest score on one map in lazer and stable, overwrite the score only in lazer (removes a score the was not counted)

**Comment by cl8n** [comment]
I don't it's clear what *should* be happening here, given that grades and even whether a score is your personal best can be different in lazer mode. from just a user perspective, it makes me want a separate set of these stats for lazer mode, but idk if that's too hard to maintain.

this also makes me wonder about how ranked score behaves if I pass a map first on lazer and then on stable...

**Comment by peppy** [comment]
> this also makes me wonder about how ranked score behaves if I pass a map first on lazer and then on stable...

Until we move all processing away from legacy systems, this is "best effort" aka undefined behaviour.

**Comment by hburn7** [comment]
Another case: https://osu.ppy.sh/users/18152711 
![image](https://github.com/user-attachments/assets/2342180f-93c9-4b3e-a114-836f4f4fe030)

**Comment by peppy** [comment]
Yes, it is still happening because we still haven't turned off broken legacy systems.

**Comment by iSlodinxOsu** [comment]
same stuff with https://osu.ppy.sh/users/5795337
![image](https://github.com/user-attachments/assets/9dc53d31-4557-4660-aee9-c98d78c9f6a8)

**Comment by Joehuu** [comment]
Reopening as it is happening again, see https://github.com/ppy/osu/discussions/33589 / https://osu.ppy.sh/users/5795337.

**Comment by CaptainBasculin** [comment]
I've recently triggered this bug on [my profile](https://osu.ppy.sh/users/10801545), on the plays listed below for the same map the mod rework buffed the SO score so that it overtakes the HDCL score but that change didn't reflect on the grade counter (it was zero to begin with), resulting in a -1 SS count after I overtook it with a HD score. 

<img width="989" height="75" alt="Image" src="https://github.com/user-attachments/assets/9a93ce47-d10f-4373-80ec-29f74e7696a7" />

Hope this helps in finding the underlying cause

**Comment by peppy** [comment]
> I've recently triggered this bug on [my profile](https://osu.ppy.sh/users/10801545), on the plays listed below for the same map the mod rework buffed the SO score so that it overtakes the HDCL score but that change didn't reflect on the grade counter (it was zero to begin with), resulting in a -1 SS count after I overtook it with a HD score.

Thanks for providing this case. There's no easy way to solve this, but a background reprocess is currently running and should get things back in a sane state over the coming days.
