### ISSUE TITLE
CL scores capped at 300k in experimental lazer deploy

### ISSUE THREAD

**Issue by Rekunan** [ppy/osu-web#9681]
Feel free to browse newly ranked to see this, but some examples:
https://lazer.ppy.sh/beatmapsets/1800527#osu/3721858 (CL SS is 300k)
https://lazer.ppy.sh/beatmapsets/1844826#osu/3789556 (CL highest is 291k)
https://lazer.ppy.sh/beatmapsets/162368#osu/922600 (CL highest is 299k)

I think the issue is that it's only calculating the accuracy portion of score.

**Comment by peppy** [comment]
This is due to a processing error which is still being fixed in the background and may take several weeks to complete.

**Comment by peppy** [comment]
Current progress: `1103326399 / 2165457509`
Estimated completion: no idea but quite a while

**Comment by Jeglerjeg** [comment]
Does the processing error still affect all newly imported scores? Brand new scores are still capped at 300k, for example https://lazer.ppy.sh/scores/2056411809

**Comment by peppy** [comment]
It should not, we're investigating this further.

**Comment by Jeglerjeg** [comment]
This still occurs (see https://lazer.ppy.sh/scores/2165685696). If the new version just hasn't been deployed yet, my bad.
